Oneness.NET.v0/Oneness.MVC/Areas/Admin/Controllers/LanguageController.cs
using Oneness.CoreData.Entity.POCO;
using Oneness.Protocols.RepositoryProtocols;
using Oneness.UnitOfWork.Core;
using Oneness.UnitOfWork.Protocols;
using Oneness.ViewModel.EntityViewModels.QuizViewModels;
using Shared.Extensions.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Oneness.ViewModel.EntityViewModels.Extensions;
using Oneness.Protocols.RepositoryProtocols.Base;
using Oneness.UnitOfWork.Base;
using Ninject;

namespace Oneness.MVC.Areas.Admin.Controllers {
    [OutputCache(Duration = 60)]
    public class LanguageController : Controller {

        #region Actions

        // GET: Admin/Language
        [HttpGet]
        public async Task<ActionResult> Index() {

            var response = await UnitOfWork.AllLanguages();

            return View(response.Select(m => m.ToViewModel()));

        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public async Task<ActionResult> Add() {

            if (Request.IsAjaxRequest()) {

                var name = Request["Name"].ToType<String>();
                var description = Request["Description"].ToType<String>();
                var langID = Request["CurrentLanguageID"].ToType<Int64>();

                IRepositoryBaseAsync<Language> response;
                if (langID == default(Int64)) {
                    response = await UnitOfWork.InsertLanguage(new Language() {
                        Name = name,
                        Description = description
                    });
                } else {
                    response = await UnitOfWork.UpdateLanguage(langID, lg => lg.Assign(l => l.Name = name).Assign(l => l.Description = description));
                }

                return View("Index");

            } else {
                return View("Index");
            }
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public async Task<ActionResult> Delete() {

            if (Request.IsAjaxRequest()) {
                var langID = Request["LanguageIDToBeDeleted"].ToType<Int64>();

                var response = await UnitOfWork.DeleteLanguage(langID);

                return View("Index");

            } else {
                return View("Index");
            }
        }


        #endregion

        #region UnitOfWork

        private IManifestOfWork UnitOfWork {
            get {
                return SUnitProvider.Container.Get<IManifestOfWork>();
            }
        }

        #endregion

    }
}

Oneness.NET.v0/Oneness.MVC/Areas/Admin/Controllers/ManifestController.cs
using Oneness.CoreData.Entity.POCO;
using Oneness.Protocols.RepositoryProtocols;
using Oneness.Protocols.RepositoryProtocols.Base;
using Oneness.UnitOfWork.Core;
using Oneness.UnitOfWork.Protocols;
using Oneness.ViewModel.EntityViewModels.QuizViewModels;
using Shared.Extensions.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Oneness.UnitOfWork.Base;
using Ninject;

namespace Oneness.MVC.Areas.Admin.Controllers {
    [OutputCache(Duration = 60)]
    public class ManifestController : Controller {

        #region Actions

        // GET: Admin/Manifest
        [HttpGet]
        public async Task<ActionResult> Index() {

            var response = await UnitOfWork.AllManifests();

            return View(response.Select(m => m.ToViewModel()).ToArray());

        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public async Task<ActionResult> Add() {

            if (Request.IsAjaxRequest()) {
                IRepositoryBaseAsync<Manifest> response;

                Int64 manifestID = Convert.ToInt64(Request["CurrentManifestID"]);

                Int64 languageID = Convert.ToInt64(Request["SelectedLanguageID"]);
                Int64 sentenceID = Convert.ToInt64(Request["SelectedSentenceID"]);

                if (manifestID != default(Int64)) {
                    response = await UnitOfWork.UpdateManifest(manifestID, languageID, sentenceID, mf => mf);
                } else {
                    response = await UnitOfWork.InsertManifest(languageID, sentenceID);
                }
                return View("Index");

            } else {
                return View("Index");
            }
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public async Task<ActionResult> Delete() {

            if (Request.IsAjaxRequest()) {

            Int64 manifestID = Convert.ToInt64(Request["ManifestIDToBeDeleted"]);
                manifestID.AssertNotNull();
                await UnitOfWork.DeleteManifest(manifestID);

                return View("Index");

            } else {
                return View("Index");
            }
        }


        #endregion

        #region UnitOfWork

        private IManifestOfWork UnitOfWork {
            get {
                return SUnitProvider.Container.Get<IManifestOfWork>();
            }
        }

        #endregion


    }
}

Oneness.NET.v0/Oneness.MVC/Areas/Admin/Controllers/SentenceController.cs
using Oneness.CoreData.Entity.POCO;
using Oneness.Protocols.RepositoryProtocols;
using Oneness.UnitOfWork.Core;
using Oneness.UnitOfWork.Protocols;
using Oneness.ViewModel.EntityViewModels.QuizViewModels;
using Shared.Extensions.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Oneness.ViewModel.EntityViewModels.Extensions;
using Oneness.UnitOfWork.Base;
using Ninject;

namespace Oneness.MVC.Areas.Admin.Controllers {
    [OutputCache(Duration = 60)]
    public class SentenceController : Controller {


        #region Actions

        // GET: Admin/Sentence
        [HttpGet]
        public async Task<ActionResult> Index() {

            var response = await UnitOfWork.AllSentences();

            return View(response.Select(m => m.ToViewModel()));

        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public async Task<ActionResult> Add() {

            if (Request.IsAjaxRequest()) {

                var text = Request.Form["Text"].ToType<String>();
                var sentenceID = Request.Form["CurrentSentenceID"].ToType<Int64>();

                if (sentenceID != default(Int64)) {
                    var response = await UnitOfWork.UpdateSentence(sentenceID, sent => sent.Assign(snt => snt.Text = text));
                } else {
                    var response = await UnitOfWork.InsertSentence(new Sentence() {
                        Text = text
                    });
                }

                return View("Index");

            } else {
                return View("Index");
            }
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public async Task<ActionResult> Delete() {

            if (Request.IsAjaxRequest()) {
                var sentenceID = Request["SentenceIDToBeDeleted"].ToType<Int64>();

                var response = await UnitOfWork.DeleteSentence(sentenceID);

                return View("Index");

            } else {
                return View("Index");
            }
        }


        #endregion


        #region UnitOfWork

        private IManifestOfWork UnitOfWork {
            get {
                return SUnitProvider.Container.Get<IManifestOfWork>();
            }
        }

        #endregion

    }
}

Oneness.NET.v0/Oneness.MVC/Controllers/QuizController.cs
using System;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Mvc;
using Ninject;
using Oneness.IoC.Core;
using Oneness.Localization.Resources;
using Oneness.CoreData.Context;
using Oneness.CoreData.Entity.POCO;
using Oneness.Protocols.RepositoryProtocols;
using Shared.Extensions.Core;
using Oneness.Definitions.WebConfig;
using System.Web.UI.WebControls;
using System.Dynamic;
using Oneness.ViewModel.EntityViewModels.QuizViewModels;
using Oneness.ViewModel.EntityViewModels.Extensions;
using Oneness.Protocols.RepositoryProtocols.Base;

namespace Oneness.MVC.Controllers {

    //[OutputCache(Duration = 60)]
    public class QuizController : Controller {

        #region Actions

        [HttpGet]
        public async Task<ActionResult> Index() {

            var response = await SInstanceProvider.Container.Get<IRepositoryBaseAsync<Quiz>>().TopAsync(e => e.ID);
            return View(response.ToViewModel());

        }

        [HttpPost]
        public async Task<JsonResult> PostAnswer(QuestionViewModel viewModel) {

            if (Request.IsAjaxRequest()) {
                var qsid = Request["CurrentQuestionID"].ToType<Int64>();
                var qzid = Request["CurrentQuizID"].ToType<Int64>();
                var selectedAnswerID = Request["SelectedAnswer"].ToType<Int64>();
                var done = (await SInstanceProvider.Container
                    .Get<IRepositoryBaseAsync<Answer>>().TheAsync(selectedAnswerID)) != null;
                return await Task.Factory.StartNew<JsonResult>(() =>
                    Json(new {
                        qzid = qzid, qsid = qsid, done = done,
                        ModalTitle = "{0}ModalTitle".PostFormat(done ? "Done" : "Failed").Translate(),
                        ModalBody = "{0}ModalBody".PostFormat(done ? "Done" : "Failed").Translate()
                    }));
            } else {
                return await Task.Factory.StartNew<JsonResult>(() =>
                    Json(new { awid = Request["SelectedAnswer"] }));
            }

        }

        #endregion

    }
}

Oneness.NET.v0/Oneness.MVC/Areas/Admin/Views/Shared/AvailableLanguageCommands.cshtml
@using Oneness.ViewModel.EntityViewModels.QuizViewModels;
@using Oneness.Localization.Resources;
@using Shared.Extensions.Core;


@model LanguageViewModel

@{
    var submit = "SaveChanges".Translate();
    var diff = "language-{0}".PostFormat(Model.ID);
}

@Html.Partial("LanguageForm", Model, new ViewDataDictionary() { { "CurrentLanguageID", Model.ID } })

<script type="text/javascript">
    function onLanguageDeleteSuccess(data) {
        window.location.href = document.location.href;
    }
    function onLanguageDeleteFailure(data) {
        $('#warning-language-delete').removeClass('alert-*').addClass('alert-danger');
        $('#warning-language-delete').html(data.statusText);
    }
</script>

<div class="row">
    @Ajax.ActionLink("DeleteItemEntry".Translate(), "Delete", "Language"
            , new { LanguageIDToBeDeleted = Model.ID }
            , new AjaxOptions() { Confirm = "LanguageWillBeDeleted".Translate(), HttpMethod = "POST", OnSuccess = "onLanguageDeleteSuccess", OnFailure = "onLanguageDeleteFailure" })

    @Html.Raw("|")
    <a href="#" onclick="return ShowForm('@diff');">@Html.Raw("EditItemEntry".Translate())</a>
</div>

Oneness.NET.v0/Oneness.MVC/Areas/Admin/Views/Shared/AvailableManifestCommands.cshtml
@using Oneness.ViewModel.EntityViewModels.QuizViewModels;
@using Oneness.Localization.Resources;
@using Shared.Extensions.Core;


@model ManifestViewModel

@{
    var submit = "SaveChanges".Translate();
    var diff = "manifest-{0}".PostFormat(Model.ID);
}

@Html.Partial("ManifestForm", Model, new ViewDataDictionary() { { "CurrentManifestID", Model.ID } })

<script type="text/javascript">
    function onManifestDeleteSuccess(data) {
        window.location.href = document.location.href;
    }
    function onManifestDeleteFailure(data) {
        $('#warning-manifest-delete').removeClass('alert-*').addClass('alert-danger');
        $('#warning-manifest-delete').html(data.statusText);
    }
</script>

<div class="row">
    @Ajax.ActionLink("DeleteItemEntry".Translate(), "Delete", "Manifest"
            , new { ManifestIDToBeDeleted = Model.ID }
            , new AjaxOptions() { Confirm = "ManifestWillBeDeleted".Translate(), HttpMethod = "POST", OnSuccess = "onManifestDeleteSuccess", OnFailure = "onManifestDeleteFailure" })

    @Html.Raw("|")
    <a href="#" onclick="return ShowForm('@diff');">@Html.Raw("EditItemEntry".Translate())</a>
</div>

Oneness.NET.v0/Oneness.MVC/Areas/Admin/Views/Shared/AvailableQuizCommands.cshtml
@using Oneness.ViewModel.EntityViewModels.QuizViewModels;
@using Oneness.Localization.Resources;
@using Shared.Extensions.Core;


@model QuizViewModel

@{
    var submit = "SaveChanges".Translate();
    var diff = "quiz-{0}".PostFormat(Model.SentenceViewModel.ID);
}

@Html.Partial("SentenceForm", Model.SentenceViewModel,
    new ViewDataDictionary() { { "CurrentSentenceID", Model.SentenceViewModel.ID }, { "CurrentQuizID", Model.ID }, { "ModelName", "quiz" } })

<script type="text/javascript">
    function onQuizDeleteSuccess(data) {
        console.log(data);
        $('#warning-quiz-delete').removeClass('alert-*').addClass(data.done ? 'alert-success' : 'alert-danger');
        if (!data.done) {
            $('#warning-quiz-delete').html(data.faultMessage);
        } else {
            window.location.href = document.location.href;
        }
    }
    function onQuizDeleteFailure(data) {
        console.log(data);
        $('#warning-quiz-delete').removeClass('alert-*').addClass(data.done ? 'alert-success' : 'alert-danger');
        if (!data.done) {
            $('#warning-quiz-delete').html(data.faultMessage);
        }
    }
</script>

<div class="row">
    @Ajax.ActionLink("DeleteItemEntry".Translate(), "Delete", "Quiz"
            , new { QuizIDToBeDeleted = Model.ID }
            , new AjaxOptions() { Confirm = "QuizWillBeDeleted".Translate(), HttpMethod = "POST", OnSuccess = "onQuizDeleteSuccess", OnFailure = "onQuizDeleteFailure" }) @Html.Raw("|") <a href="#" onclick="return ShowForm('@diff');">@Html.Raw("EditItemEntry".Translate())</a>
</div>

Oneness.NET.v0/Oneness.MVC/Areas/Admin/Views/Shared/AvailableSentenceCommands.cshtml
@using Oneness.ViewModel.EntityViewModels.QuizViewModels;
@using Oneness.Localization.Resources;
@using Shared.Extensions.Core;


@model SentenceViewModel

@{
    var submit = "SaveChanges".Translate();
    var diff = "sentence-{0}".PostFormat(Model.ID);
}

@Html.Partial("SentenceForm", Model, new ViewDataDictionary() { { "CurrentSentenceID", Model.ID } })

<script type="text/javascript">
    function onSentenceDeleteSuccess(data) {
        window.location.href = document.location.href;
    }
    function onSentenceDeleteFailure(data) {
        $('#warning-language-delete').removeClass('alert-*').addClass('alert-danger');
        $('#warning-language-delete').html(data.statusText);
    }
</script>

<div class="row">
    @Ajax.ActionLink("DeleteItemEntry".Translate(), "Delete", "Sentence"
            , new { SentenceIDToBeDeleted = Model.ID }
            , new AjaxOptions() { Confirm = "SentenceWillBeDeleted".Translate(), HttpMethod = "POST", OnSuccess = "onSentenceDeleteSuccess", OnFailure = "onSentenceDeleteFailure" })

    @Html.Raw("|")
    <a href="#" onclick="return ShowForm('@diff');">@Html.Raw("EditItemEntry".Translate())</a>
</div>

Oneness.NET.v0/Oneness.MVC/Areas/Admin/Views/Shared/LanguageForm.cshtml
@using Oneness.ViewModel.EntityViewModels.QuizViewModels;
@using Oneness.Localization.Resources;
@using Shared.Extensions.Core;


@model LanguageViewModel

@{
    var submit = "SaveChanges".Translate();
    var diff = "language-{0}".PostFormat(Model.ID);
    var bodyID = "body-{0}".PostFormat(diff);
    var modalTitle = "AddNewLanguageModalTitle".Translate();
}

<script type="text/javascript">
    function onLanguageAddSuccess(data) {
        window.location.href = document.location.href;
    }
    function onLanguageDeleteFailure(data) {
        $('#warning-language-delete').removeClass('alert-*').addClass('alert-danger');
        $('#warning-language-delete').html(data.statusText);
    }
</script>

<a href="#" class="hidden" id="bootstrap-modal-trigger-@diff"
   data-toggle="modal"
   data-target="#bootstrap-modal-@diff"></a>


@using (@Ajax.BeginForm("Add", new { CurrentLanguageID = ViewData["CurrentLanguageID"] }
                    , new AjaxOptions() { HttpMethod = "POST", OnSuccess = "onLanguageAddSuccess", OnFailure = "onLanguageDeleteFailure" }
                    , new { id = @bodyID, style = "position: absolute;" })) {
    Html.ValidationSummary(true);
    <div class="modal fade" id="bootstrap-modal-@diff" tabindex="-1" role="dialog" aria-labelledby="basicModal-@diff" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div id="bootstrap-modal-header-@diff" class="modal-header has-success">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title lampic-text-primary-glow" id="modal-title-@diff">@modalTitle</h4>
                </div>
                <div class="modal-body row">
                    <div class="col-md-2 col-xs-6"><img id="img-modal-body-@diff" src="" alt="verified" /></div>
                    <div class="col-md-7 col-xs-6">
                        <div id="modal-body-@diff">
                            <h1 class="grid-header"></h1>
                            <div class="row  col-sm-12">
                                <div class="form-group focus">
                                    @Html.LabelFor(vm => vm.Name, new { @for = "vm-name-text-" + @diff })
                                    @Html.TextBoxFor(vm => vm.Name, new { @class = "form-control", id = "vm-name-text-" + @diff, placeholder = "LanguageNamePlaceholder".Translate() })
                                    <span class="text-danger">@Html.ValidationMessageFor(m => m.Name)</span>
                                </div>
                            </div>
                            <div class="row  col-sm-12">
                                <div class="form-group">
                                    @Html.LabelFor(vm => vm.Description, new { @for = "vm-description-text-" + @diff })
                                    @Html.TextBoxFor(vm => vm.Description, new { @class = "form-control", id = "vm-description-text-" + @diff, placeholder = "LanguageDescriptionPlaceholder".Translate() })
                                    <span class="text-danger">@Html.ValidationMessageFor(m => m.Description)</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button id="modal-body-close-@diff" type="button" class="btn btn-default" data-dismiss="modal">@Html.Raw("CancelSubmit".Translate())</button>
                    <button id="modal-body-save-@diff" type="submit" class="btn btn-primary">@Html.Raw("CommitSubmit".Translate())</button>
                </div>
            </div>

        </div>
    </div>
}

Oneness.NET.v0/Oneness.MVC/Areas/Admin/Views/Shared/LanguageList.cshtml
@using Oneness.ViewModel.EntityViewModels.QuizViewModels;
@using Oneness.Localization.Resources;
@using Shared.Extensions.Core;


@model LanguageListViewModel

@{
    var submit = "SaveChanges".Translate();
    var diff = "language-{0}".PostFormat(Model.SelectedLanguageID);
    var bodyID = "body-{0}".PostFormat(diff);
}

@Html.DropDownListFor(vml => vml.SelectedLanguageID
    , Model.LanguageViewModels.Select(lvm => new SelectListItem() { Text = lvm.Name, Value = lvm.ID.ToType<String>() }), new { id= "ddl-manifest-by-" + diff })

Oneness.NET.v0/Oneness.MVC/Areas/Admin/Views/Shared/ManifestForm.cshtml
@using Oneness.ViewModel.EntityViewModels.QuizViewModels;
@using Oneness.Localization.Resources;
@using Shared.Extensions.Core;


@model ManifestViewModel

@{
    var submit = "SaveChanges".Translate();
    var diff = "manifest-{0}".PostFormat(Model.ID);
    var bodyID = "body-{0}".PostFormat(diff);
    var modalTitle = "AddNewManifestModalTitle".Translate();
    var languageID = (Model.LanguageViewModel ?? new LanguageViewModel() { ID = 0 }).ID;
    var sentenceID = (Model.SentenceViewModel ?? new SentenceViewModel() { ID = 0 }).ID;
}

<script type="text/javascript">
    function onLanguageAddSuccess(data) {
        window.location.href = document.location.href;
    }
    function onLanguageDeleteFailure(data) {
        $('#warning-manifest-delete').removeClass('alert-*').addClass('alert-danger');
        $('#warning-manifest-delete').html(data.statusText);
    }
</script>

<a href="#" class="hidden" id="bootstrap-modal-trigger-@diff"
   data-toggle="modal"
   data-target="#bootstrap-modal-@diff"></a>


@using (@Ajax.BeginForm("Add", new { CurrentManifestID = ViewData["CurrentManifestID"] }
                                , new AjaxOptions() { HttpMethod = "POST", OnSuccess = "onLanguageAddSuccess", OnFailure = "onLanguageDeleteFailure" }
                                , new { id = @bodyID, style = "position: absolute;" })) {
    Html.ValidationSummary(true);
    <div class="modal fade" id="bootstrap-modal-@diff" tabindex="-1" role="dialog" aria-labelledby="basicModal-@diff" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div id="bootstrap-modal-header-@diff" class="modal-header has-success">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title lampic-text-primary-glow" id="modal-title-@diff">@modalTitle</h4>
                </div>
                <div class="modal-body row">
                    <div class="col-md-2 col-xs-6"><img id="img-modal-body-@diff" src="" alt="verified" /></div>
                    <div class="col-md-7 col-xs-6">
                        <div id="modal-body-@diff">
                            <h1 class="grid-header"></h1>
                            <div class="row  col-sm-12">
                                <div class="input-group focus">
                                    @Html.LabelFor(vm => vm.LanguageViewModel)
                                    @Html.Partial("LanguageList", LanguageListViewModel.GetLanguageList(languageID), new ViewDataDictionary() { { "CurrentManifestID", Model.ID } })
                                    <span class="text-danger">@Html.ValidationMessageFor(m => m.LanguageViewModel)</span>
                                </div>
                            </div>
                            <div class="row  col-sm-12">
                                <div class="input-group">
                                    @Html.LabelFor(vm => vm.SentenceViewModel)
                                    @Html.Partial("SentenceList", SentenceListViewModel.GetSelectList(sentenceID), new ViewDataDictionary() { { "CurrentManifestID", Model.ID } })
                                    <span class="text-danger">@Html.ValidationMessageFor(m => m.SentenceViewModel)</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button id="modal-body-close-@diff" type="button" class="btn btn-default" data-dismiss="modal">@Html.Raw("CancelSubmit".Translate())</button>
                    <button id="modal-body-save-@diff" type="submit" class="btn btn-primary">@Html.Raw("CommitSubmit".Translate())</button>
                </div>
            </div>

        </div>
    </div>
}

Oneness.NET.v0/Oneness.MVC/Areas/Admin/Views/Shared/SentenceForm.cshtml
@using Oneness.ViewModel.EntityViewModels.QuizViewModels;
@using Oneness.Localization.Resources;
@using Shared.Extensions.Core;


@model SentenceViewModel

@{
    var submit = "SaveChanges".Translate();
    var diff = "{1}-{0}".PostFormat(Model.ID, ViewData["ModelName"] ?? "sentence");
    var bodyID = "body-{0}".PostFormat(diff);
    var modalTitle = "AddNewSentenceModalTitle".Translate();
    var warning = "warning-{0}-delete".PostFormat(ViewData["ModelName"] ?? "sentence");
}

<script type="text/javascript">
    function onSentenceAddSuccess(data) {
        window.location.href = document.location.href;
    }
    function onSentenceDeleteFailure(data) {
        $('#@warning').removeClass('alert-*').addClass('alert-danger');
        $('#@warning').html(data.statusText);
    }
</script>

<a href="#" class="hidden" id="bootstrap-modal-trigger-@diff"
   data-toggle="modal"
   data-target="#bootstrap-modal-@diff"></a>


@using (@Ajax.BeginForm("Add", new { CurrentSentenceID = ViewData["CurrentSentenceID"], CurrentQuizID = ViewData["CurrentQuizID"] }
                    , new AjaxOptions() { HttpMethod = "POST", OnSuccess = "onSentenceAddSuccess", OnFailure = "onSentenceDeleteFailure" }
                    , new { id = @bodyID, style = "position: absolute;" })) {
    Html.ValidationSummary(true);
    <div class="modal fade" id="bootstrap-modal-@diff" tabindex="-1" role="dialog" aria-labelledby="basicModal-@diff" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div id="bootstrap-modal-header-@diff" class="modal-header has-success">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title lampic-text-primary-glow" id="modal-title-@diff">@modalTitle</h4>
                </div>
                <div class="modal-body row">
                    <div class="col-md-2 col-xs-6"><img id="img-modal-body-@diff" src="" alt="verified" /></div>
                    <div class="col-md-7 col-xs-6">
                        <div id="modal-body-@diff">
                            <h1 class="grid-header"></h1>
                            <div class="row  col-sm-12">
                                <div class="form-group focus">
                                    @Html.LabelFor(vm=>vm.Text, new { @for = "vm-name-text-" + @diff })
                                    @Html.TextBoxFor(vm => vm.Text, new { @class = "form-control", id="vm-name-text-" + @diff, placeholder = "SentenceTextPlaceholder".Translate() })
                                    <span class="text-danger">@Html.ValidationMessageFor(m => m.Text)</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button id="modal-body-close-@diff" type="button" class="btn btn-default" data-dismiss="modal">@Html.Raw("CancelSubmit".Translate())</button>
                    <button id="modal-body-save-@diff" type="submit" class="btn btn-primary">@Html.Raw("CommitSubmit".Translate())</button>
                </div>
            </div>

        </div>
    </div>
}

Oneness.NET.v0/Oneness.MVC/Areas/Admin/Views/Shared/SentenceList.cshtml
@using Oneness.ViewModel.EntityViewModels.QuizViewModels;
@using Oneness.Localization.Resources;
@using Shared.Extensions.Core;


@model SentenceListViewModel

@{
    var submit = "SaveChanges".Translate();
    var diff = "sentence-{0}".PostFormat(Model.SelectedSentenceID);
    var bodyID = "body-{0}".PostFormat(diff);
}

@Html.DropDownListFor(vml => vml.SelectedSentenceID
    , Model.SentenceViewModels.Select(lvm => new SelectListItem() { Text = lvm.Text, Value = lvm.ID.ToType<String>() }), new { id = "ddl-manifest-by-" + diff })